name: Deploy to Alwaysdata

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.ALWAYSDATA_SSH_HOST }}
          username: ${{ secrets.ALWAYSDATA_SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/www
            git pull origin master
            composer install --no-dev --optimize-autoloader
            php bin/console cache:clear --env=prod